name: Build & Push to Docker Hub

on:
  push:
    branches: ["master"]
    tags: ["v*"]

permissions:
  contents: read

env:
  FRONTEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/pm-dashboard-frontend
  BACKEND_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/pm-dashboard-backend
  GIT_SHA: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 🔧 Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -------- FRONTEND (nginx) --------
      - name: 🧱 Build & Push FRONTEND
        uses: docker/build-push-action@v6
        with:
          context: .
          file: client/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:latest
            ${{ env.FRONTEND_IMAGE }}:${{ env.GIT_SHA }}
          # Enable GitHub cache to speed up
          cache-from: type=registry,ref=${{ env.FRONTEND_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.FRONTEND_IMAGE }}:buildcache,mode=max

      # -------- BACKEND (Django) --------
      - name: 🧱 Build & Push BACKEND
        uses: docker/build-push-action@v6
        with:
          context: .
          file: server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.BACKEND_IMAGE }}:latest
            ${{ env.BACKEND_IMAGE }}:${{ env.GIT_SHA }}
          cache-from: type=registry,ref=${{ env.BACKEND_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.BACKEND_IMAGE }}:buildcache,mode=max
